# Generated by Django 3.2.5 on 2021-08-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shippingPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
